In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/Housing.csv')

In [ ]:
data.head(10)

price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000   7420         4          2        3      yes        no       no   
1  12250000   8960         4          4        4      yes        no       no   
2  12250000   9960         3          2        2      yes        no      yes   
3  12215000   7500         4          2        2      yes        no      yes   
4  11410000   7420         4          1        2      yes       yes      yes   
5  10850000   7500         3          3        1      yes        no      yes   
6  10150000   8580         4          3        4      yes        no       no   
7  10150000  16200         5          3        2      yes        no       no   
8   9870000   8100         4          1        2      yes       yes      yes   
9   9800000   5750         3          2        4      yes       yes       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  
5              no             yes        2      yes   semi-furnished  
6              no             yes        2      yes   semi-furnished  
7              no              no        0       no      unfurnished  
8              no             yes        2      yes        furnished  
9              no             yes        1      yes      unfurnished

In [ ]:
data['mainroad']=data['mainroad'].apply({'yes':1,'no':0}.get)
data['guestroom']=data['guestroom'].apply({'yes':1,'no':0}.get)
data['basement']=data['basement'].apply({'yes':1,'no':0}.get)
data['hotwaterheating']=data['hotwaterheating'].apply({'yes':1,'no':0}.get)
data['airconditioning']=data['airconditioning'].apply({'yes':1,'no':0}.get)
data['prefarea']=data['prefarea'].apply({'yes':1,'no':0}.get)
data['furnishingstatus']=data['furnishingstatus'].apply({'unfurnished':0,'furnished':1,'semi-furnished':2}.get)

In [ ]:
data.head(10)

price   area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000   7420         4          2        3         1          0   
1  12250000   8960         4          4        4         1          0   
2  12250000   9960         3          2        2         1          0   
3  12215000   7500         4          2        2         1          0   
4  11410000   7420         4          1        2         1          1   
5  10850000   7500         3          3        1         1          0   
6  10150000   8580         4          3        4         1          0   
7  10150000  16200         5          3        2         1          0   
8   9870000   8100         4          1        2         1          1   
9   9800000   5750         3          2        4         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   
5         1                0                1        2         1   
6         0                0                1        2         1   
7         0                0                0        0         0   
8         1                0                1        2         1   
9         0                0                1        1         1   

   furnishingstatus  
0                 1  
1                 1  
2                 2  
3                 1  
4                 1  
5                 2  
6                 2  
7                 0  
8                 1  
9                 0

Using Regression

In [ ]:
x=data[['area','bedrooms','bathrooms','stories','mainroad','guestroom','basement','hotwaterheating','airconditioning','parking','prefarea','furnishingstatus']]
y=data['price']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

Creating a machine learning model by using Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
regression=LinearRegression()

In [ ]:
regression.fit(x_train,y_train)

LinearRegression()

In [ ]:
prediction=regression.predict(x_test)

In [ ]:
regression.score(x,y)

0.6781496638040703

In [ ]:
data_new={'area':32949,'bedrooms':5,'bathrooms':4,'stories':3,'mainroad':1,'guestroom':1,'basement':1,'hotwaterheating':1,'airconditioning':1,'parking':3,'prefarea':1,'furnishingstatus':1}

In [ ]:
index=[1]
my_data=pd.DataFrame(data_new,index)

In [ ]:
my_data

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
1  32949         5          4        3         1          1         1   

   hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
1                1                1        3         1                 1

In [ ]:
new_predictions=regression.predict(my_data)
print('The  price of house is', new_predictions)

The  price of house is [18167158.198519]


Using Classification

In [ ]:
x=data[['price','area','bedrooms','bathrooms','stories','guestroom','basement','hotwaterheating','airconditioning','parking','prefarea','furnishingstatus']]
y=data['mainroad']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

Creating a machine learning model by using KNN Algorithm

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5) #here k=5

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
knn.predict(x_test) #y hat (predicted output by MLM(Machine Learning M0del))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
predictions=knn.predict(x_test)

In [ ]:
#calculating accuracy of model
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [ ]:
print(cm)

[[  5  21]
 [  3 135]]


In [ ]:
print(ac)

0.8536585365853658


In [ ]:
data_new={'price':217538,'area':942,'bedrooms':3,'bathrooms':2,'stories':4,'guestroom':0,'basement':0,'hotwaterheating':0,'airconditioning':0,'parking':1,'prefarea':0,'furnishingstatus':1}

In [ ]:
index=[1]
my_data=pd.DataFrame(data_new,index)

In [ ]:
my_data

price  area  bedrooms  bathrooms  stories  guestroom  basement  \
1  217538   942         3          2        4          0         0   

   hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
1                0                0        1         0                 1

In [ ]:
new_predictions=knn.predict(my_data)

if new_predictions==1:
 print('The House will be available on main road')

else:
  print('The House will be not available on main road')

The House will be available on main road


Creating a machine learning model by using Decission Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [ ]:
tree_classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
tree_predictions=tree_classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,tree_predictions)
ac=accuracy_score(y_test,tree_predictions)

In [ ]:
print(cm)

[[  7  19]
 [ 12 126]]


In [ ]:
print(ac)

0.8109756097560976


In [ ]:
data_new={'price':4060000,'area':4992,'bedrooms':3,'bathrooms':2,'stories':2,'guestroom':0,'basement':1,'hotwaterheating':0,'airconditioning':0,'parking':2,'prefarea':0,'furnishingstatus':0}

In [ ]:
index=[1]
my_data=pd.DataFrame(data_new,index)

In [ ]:
my_data

price  area  bedrooms  bathrooms  stories  guestroom  basement  \
1  4060000  4992         3          2        2          0         1   

   hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
1                0                0        2         0                 0

In [ ]:
new_predictions=tree_classifier.predict(my_data)

if new_predictions==1:
 print('The House will be available on main road')

else:
  print('The House will be not available on main road')

The House will be available on main road


Creating a machine learning model by using Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
forest_classifier=RandomForestClassifier()

In [ ]:
forest_classifier.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
forest_predictions=forest_classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,forest_predictions)
ac=accuracy_score(y_test,forest_predictions)

In [ ]:
print(cm)

[[  3  23]
 [  4 134]]


In [ ]:
print(ac)

0.8353658536585366


In [ ]:
data_new={'price':4060760,'area':3692,'bedrooms':2,'bathrooms':1,'stories':1,'guestroom':1,'basement':0,'hotwaterheating':1,'airconditioning':0,'parking':0,'prefarea':1,'furnishingstatus':2}

In [ ]:
index=[1]
my_data=pd.DataFrame(data_new,index)

In [ ]:
my_data

price  area  bedrooms  bathrooms  stories  guestroom  basement  \
1  4060760  3692         2          1        1          1         0   

   hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
1                1                0        0         1                 2

In [ ]:
new_predictions=forest_classifier.predict(my_data)

if new_predictions==1:
 print('The House will be available on main road')

else:
  print('The House will be not available on main road')

The House will be available on main road
